### ISSUE TITLE
Rewrote in Node.js - works on Lambda!

### ISSUE THREAD

**Issue by nabilfreeman** [epsagon/clear-lambda-storage#12]
Hi there, I wrote this script again in Node.js.

https://github.com/nabilfreeman/lambda-pruner

It works out of the box on Lambda.

It doesn't use Serverless, but you can create a Lambda function manually and then run:

```
LAMBDA_NAME=my-script REGION=eu-west-1 bash deploy.sh
```

and it will do all the hard work for you. Remember to configure your Lambda properly...

You need the following permissions on your execution role:

- `AWSLambdaFullAccess` - for managing Lambdas
- `AmazonEC2ReadOnlyAccess` - for listing out EC2 regions
- `CloudWatchLogsFullAccess` - for logging

I recommend a 5 minute timeout on the Lambda function.

It also works locally, just run `npm test` and you can clean your Lambda functions.

Hope this helps!

**Comment by ranrib** [comment]
Thanks @nabilfreeman !
