### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by drodger** [epsagon/clear-lambda-storage#21]
I'd like to propose that a release be made of clear-lambda-storage to PyPI. This would allow anyone to easily install the project, and be able to use a specific version of the project. Then as the project progresses, people can decide which version suits their needs. 
What do you think?

**Comment by ranrib** [comment]
Great idea! we'll work on that

**Comment by alex4108** [comment]
@ranrib I can take this and do it in TravisCI if you'd like.  I have a few projects that I distribute on PyPi currently, pretty easy to set up provided the repo owner can turn on the integration

**Comment by ranrib** [comment]
Sure @alex4108 ! that would be very helpful. I've added you as a maintainer to this repo :)

**Comment by alex4108** [comment]
@ranrib It looks like my edu license for Travis won't let me target this repo to build.  
I will fork this repo and submit a PR for the TravisCI configuration

**Comment by ranrib** [comment]
I've set up an initial `.travis.yml` file for you so you'll be able to edit. You can see the builds in here https://travis-ci.com/github/epsagon/clear-lambda-storage

**Comment by alex4108** [comment]
[PR #22](https://github.com/epsagon/clear-lambda-storage/pull/22) will fix this
