### ISSUE TITLE
Update instructions on using the pip install version

### ISSUE THREAD

**Issue by ranrib** [epsagon/clear-lambda-storage#23]
Awesome job @alex4108! https://pypi.org/project/clear-lambda-storage/
I think it's worth updating the README to show how to use it with pip install rather than git clone.

Also - I just noted that the deploy runs on all three builds (3 different python versions) - it should probably just run through one of them (or we can just do one).

**Comment by alex4108** [comment]
Hiya!

This is updated
* I included pip install instructions in the README
* I limited Travis to only build in 3.7 and only deploy if the built branch is `master`

Anything else @ranrib ? :)

**Comment by ranrib** [comment]
Awesome! just saw that here https://github.com/epsagon/clear-lambda-storage/commit/73c721c7c94b613d67f730968af5ba405b401902
👏
