### ISSUE TITLE
'Namespace' object has no attribute 'num_to_keep': AttributeError on lambda function.

### ISSUE THREAD

**Issue by thanh3d** [epsagon/clear-lambda-storage#8]
I got this: 

> 'Namespace' object has no attribute 'num_to_keep': AttributeError
> Traceback (most recent call last):
> File "/var/task/handler.py", line 6, in clear_lambda_storage
> remove_old_lambda_versions(Namespace(token_key_id=None, token_secret=None))
> File "/var/task/clear_lambda_storage.py", line 107, in remove_old_lambda_versions
> if args.num_to_keep:
> AttributeError: 'Namespace' object has no attribute 'num_to_keep'

**Comment by ranrib** [comment]
Hi @thanh3d, can you please share you cmd command?

**Comment by thanh3d** [comment]
I deployed serverless and tried to test the function on aws .

**Comment by thanh3d** [comment]
I deployed serverless and tried to test the function on aws .

**Comment by nabilfreeman** [comment]
I had the same problem, gave up and just integrated it into my CI pipeline instead

**Comment by nabilfreeman** [comment]
Hey @thanh3d , potential solution for you here #12

**Comment by jsburckhardt** [comment]
Not sure if this helps. I included the values in the handler. I agree you could integrated in the ci pipeline.
`
remove_old_lambda_versions(Namespace(token_key_id=None, token_secret=None, num_to_keep=2, profile=None))
`
